---
abstract: 'A simple mason server'
author:
  - 'Jesse Vincent <jesse@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Server-Simple-Mason
no_index:
  directory:
    - inc
    - t
requires:
  HTML::Mason: 1.25
  HTTP::Server::Simple: 0.04
  Hook::LexWrap: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.13
